# Generated by Django 3.1.2 on 2020-11-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_dashboard_input_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='input_user',
            new_name='user',
        ),
    ]
