# Generated by Django 3.1.2 on 2021-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_dashboard_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='public_url',
            field=models.UUIDField(default=None, editable=False, null=True),
        ),
    ]
