# This is a development dockerfile
FROM python:3.9-alpine

ENV PYTHONUNBUFFERED 1

# Installing required packages
RUN apk add --update --no-cache postgresql-client jpeg-dev gettext \
    libstdc++
RUN apk add --update --no-cache --virtual .tmp-build-deps \
    build-base libc-dev linux-headers postgresql-dev zlib zlib-dev \
    python3-dev libffi-dev freetype-dev \
    pkgconfig gfortran

RUN pip install --upgrade pip
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

RUN apk del .tmp-build-deps

WORKDIR /dash
COPY . .

EXPOSE 8000